# Header
menu:
  首页: /malnote
  博客: /malnote/archives
rss:
github: https://github.com/malcolmyu

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: left
widgets:
- category
- archive
- recent_posts
- tag
- tagcloud
- links

# Links
links:
  Hexo: http://hexo.io

# 多说
duoshuo_shortname: malcolmyu

# Miscellaneous
google_analytics:
favicon: /malnote/favicon.ico
twitter: https://twitter.com/minghaoyu
google_plus:
fb_admins:
fb_app_id:
